### ISSUE TITLE
Issue with 2.15

### ISSUE THREAD

**Issue by anandshewale** [bwh-dope/pharmacoepi_toolbox#16]
Hi, I am trying to use hdps macro and java file from the following website: http://www.drugepi.org/dope-downloads/
I am stuck a this point
NOTE: Pharamcoepi Toolbox version 2.4.15 starting at Fri Jan 22 11:22:35 CST 2016.
NOTE: hd-PS
initializing.
NOTE: Opened database with cache size    70.27 MB (60 percent of available)
NOTE: hd-PS reading
patients.
org.drugepi.hdps.HdpsException: Failed to read patient information.  Check formatting and
content of patient file.
     at
org.drugepi.hdps.local.HdpsLocalPatientController.readPatients(HdpsLocalPatientController.java:4
8)
     at org.drugepi.hdps.HdpsController.run(HdpsController.java:315)
     at org.drugepi.hdps.Hdps.run(Hdps.java:361)

After this error message, the temp files like output_all_vars, output_full_cohort, etc are not created.
I tried couple options;
1) Making all the variables categorical 
2) Forward and backward slash in the path statements
3)Also there are no spaces in the path statements.

Please advice

**Comment by wleemaymay** [comment]
Hi,

I am stuck in the same problem and got exactly the same error message. I am wondering if you solve this problem already? Do you mind share? Thank you!!! Appreciate!

**Comment by anandshewale** [comment]
Hi,

I was not able to completely resolve the issue. But I was able to get to a point till I can get the propensity score of each covariate. Drop me an email at anandshewale86@gmail.com.
Anand

**Comment by oldschoolcool2** [comment]
Has this issue been resolved? I get the same error.

**Comment by dogmaster2019** [comment]
Have you been able to resolve this issue?

**Comment by oldschoolcool2** [comment]
> Have you been able to resolve this issue?

I think the error stems from patient ID's that begin with numbers instead of letters. I resolved the issue by adding a letter in front of the patient ID and then processing the hdps macro as usual. You also have to do this in the dimension datasets using the same length and format:

`    length PATID $255.;
    PATID = "f" || put(ENROLID, z11.);`

Let me know if this works out for you or not.
